export const PENDING = 'PENDING';

// Login
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_CANDLE_STICK = 'GET_CANDLE_STICK';
export const GET_CANDLE_STICK_SUCCESS = 'GET_CANDLE_STICK_SUCCESS';
export const GET_CANDLE_STICK_FAILED = 'GET_CANDLE_STICK_FAILED';