export const FETCH_USER_DATA = 'FETCH_USER_DATA';

export const SELECTED_USER_INFORMATION = 'SELECTED_USER_INFORMATION';

export const SAVE_PROJECT = 'SAVE_PROJECT';

export const REMOVE_PROJECT = 'REMOVE_PROJECT';

export const USER_SETTING = 'USER_SETTING';

export const PENDING = 'PENDING';
export const USER_SETTING_SUCCESS = 'USER_SETTING_SUCCESS';
export const USER_SETTING_FAILED = 'USER_SETTING_FAILED';